language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - libxml2-dev
    - libxml2-utils
    - libxslt1-dev
    - python-dev
    - zip
    - sqlite3
    - python-pip
    - libcurl4-openssl-dev
    - libssl-dev
    - git
install:
  - wget https://github.com/galeksandrp/https-everywhere/archive/check-sublist3r.tar.gz -O - | tar xz -C ~
  - mv ~/https-everywhere-check-sublist3r ~/workspace
  - pip install requests
  - pip install dnspython
  - pip install argparse
  - wget https://github.com/aboul3la/Sublist3r/archive/master.tar.gz -O | tar xz -C ~
  - mv ~/Sublist3r-master ~/Sublist3r
  - git remote add upstream https://github.com/EFForg/https-everywhere.git
  - git fetch upstream
  - git checkout upstream/master
  - pip install --user --no-allow-insecure --no-allow-external -r requirements.txt
  - pip install --user -r test/rules/requirements.txt
  - pip install --user -r test/chromium/requirements.txt
  - wget https://github.com/github/hub/releases/download/v2.2.8/hub-linux-amd64-2.2.8.tgz -O - | tar xz --strip=1 -C ~ hub-linux-amd64-2.2.8
  - export PATH=~/bin:$PATH
  - chmod +x ~/workspace/Sublist3r/sublist3r.py ~/workspace/*.sh
script:
  - cd src/chrome/content/rules
  - ~/workspace/generate.sh $TRAVIS_BRANCH
deploy:
  provider: script
  script: git add $TRAVIS_BUILD_DIR/src/chrome/content/rules/$TRAVIS_BRANCH.xml && git commit -m TRAVIS_BRANCH && git push origin $TRAVIS_BRANCH
branches:
  except:
    - master
notifications:
  email: false
