sudo: required
language: generic
services:
  - docker
script:
  - travis_wait 120 sleep infinity &
  - docker run --rm -ti -v $(pwd):/opt -e "GITHUB_NAME=$GITHUB_NAME" -e "GITHUB_TOKEN=$GITHUB_TOKEN" -e "DOMAIN=$DOMAIN" -e "ISSUE=$ISSUE" galeksandrp/https-everywhere:docker-httpse bash -c "test/travis.sh"
notifications:
  email: false
