addons:
  apt:
    packages:
    - python-requests
    - python-dnspython
    - python-argparse
install:
  - wget https://github.com/galeksandrp/https-everywhere/archive/check-sublist3r.tar.gz | tar xz -C~ https-everywhere-check-sublist3r
  - mv ~/https-everywhere-check-sublist3r ~/workspace
  - git remote add upstream https://github.com/EFForg/https-everywhere.git
  - git fetch upstream
  - git checkout upstream/master
  - pip install --no-allow-insecure --no-allow-external -r requirements.txt
  - pip install -r test/rules/requirements.txt
  - pip install -r test/chromium/requirements.txt
  - wget https://github.com/github/hub/releases/download/v2.2.8/hub-linux-amd64-2.2.8.tgz | tar xz --strip=1 -C~ hub-linux-amd64-2.2.8
  - export PATH=~/bin:$PATH
  - chmod +x ~/workspace/*.sh
script:
  - cd src/chrome/content/rules
  - ~/workspace/generate.sh $TRAVIS_BRANCH
deploy:
  provider: script
  script: git add $TRAVIS_BUILD_DIR/src/chrome/content/rules/$TRAVIS_BRANCH.xml && git commit -m TRAVIS_BRANCH && git push origin $TRAVIS_BRANCH
branches:
  except:
    - master
notifications:
  email: false
