sudo: required
language: generic
services:
  - docker
script:
  - docker run --rm -ti -e "GIT_EMAIL=$GIT_EMAIL" -e "GIT_NAME=$GIT_NAME" -e "GITHUB_NAME=$GITHUB_NAME" -e "GITHUB_TOKEN=$GITHUB_TOKEN" -e "GITHUB_OWNER=$GITHUB_OWNER" -e "TRAVIS_BRANCH=$TRAVIS_BRANCH" galeksandrp/travistest:docker-httpse bash -c "test/rules.sh"
notifications:
  email: false
